### ISSUE TITLE
在投稿页面会显示不正常

### ISSUE THREAD

**Issue by cmmdwl** [Chaosinism/BilibiliCommentAnalyzer_js#1]
https://member.bilibili.com/v2#/upload/video/interactive 
这个页面没有内容，但是会出现显示异常

**Comment by cmmdwl** [comment]
// @match        *://*.bilibili.com/bangumi/play/*
// @exclude      *://member.bilibili.com/*
添加这两个就能修复投稿页面2问题，并顺便修复番剧页没有开关的问题

**Comment by Chaosinism** [comment]
@cmmdwl 感谢指出投稿页面的问题，现已修改。番剧区返回的信息格式和普通视频有一些不同，暂时还没法加入相同功能，可能之后会考察一下。
